### ახალი მომხმარებლის დამატება
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test50@test.com",
  "password": "12345"
}

### შესვლა
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test50@test.com",
  "password": "12345"
}

### შესული მომხმარებლებლის ჩვენება
GET http://localhost:3000/auth/whoami

### გამოსვლა
POST http://localhost:3000/auth/signout

### მომხმარებლის ძიება აიდით
GET http://localhost:3000/auth/4

### პოვნა ყველა მომხარებლის მოცემული მეილით
GET http://localhost:3000/auth?email=asdf@asdf.com

### მომხამრებლის წაშლა აიდითი
DELETE http://localhost:3000/auth/3

### პაროლის შეცვლა
PATCH http://localhost:3000/auth/4
content-type: application/json

{
  "password": "aaaaa"
}
